Update and rename build.yml to d.yml

diff --git a/.github/workflows/d.yml b/.github/workflows/d.yml
--- a/.github/workflows/d.yml
+++ b/.github/workflows/d.yml
@@ -1,4 +1,4 @@
-name: OEM GSI Builder
+name: uname
 
 on:
   workflow_dispatch:
@@ -9,7 +9,7 @@ defaults:
     
 jobs:
   build:
-    runs-on: ubuntu-18.04
+    runs-on: ubuntu-20.04
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -18,22 +18,20 @@ jobs:
         id: config
         with:
           path: config.env
-      - name: Check Configuration
-        run: |
-          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
-          required "${{ secrets.USERNAME }}" "USERNAME secret"
-          required "${{ secrets.PASSWORD }}" "PASSWORD secret"
+     #- name: Check Configuration
+     #   run: |
+     #     function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
+     #     required "${{ secrets.USERNAME }}" "USERNAME secret"
+     #     required "${{ secrets.PASSWORD }}" "PASSWORD secret"
 
-          required "${{ steps.config.outputs.tool_repo }}" "TOOL_REPO config"
-          required "${{ steps.config.outputs.url }}" "URL config"
-          required "${{ steps.config.outputs.firmware_type }}" "FIRMWARE_TYPE config"
-          required "${{ steps.config.outputs.sourceforge_dir }}" "SOURCEFORGE_DIR config"
-          required "${{ steps.config.outputs.output_type }}" "OUTPUT_TYPE config"
-      - name: Setup ErfanGSIs Tools
+     #     required "${{ steps.config.outputs.tool_repo }}" "TOOL_REPO config"
+     #     required "${{ steps.config.outputs.url }}" "URL config"
+     #     required "${{ steps.config.outputs.firmware_type }}" "FIRMWARE_TYPE config"
+     #     required "${{ steps.config.outputs.sourceforge_dir }}" "SOURCEFORGE_DIR config"
+     #     required "${{ steps.config.outputs.output_type }}" "OUTPUT_TYPE config"
+      - name: uname
         run: |
-          git clone --recurse-submodules "${{ steps.config.outputs.tool_repo }}" ErfanGSIs
-          bash ErfanGSIs/setup.sh
-          sed -i '$d' ErfanGSIs/url2GSI.sh
+          cat /proc/cpuinfo|grep processor|wc -l
       - name: Build A/B
         if: ${{ steps.config.outputs.output_type == 'all' }}
         run: |
